# =============================================================================
# Blue Cripto Status Page - Powered by Upptime
# =============================================================================

owner: mychelmendes1
repo: blue-cripto-status

# =============================================================================
# Sites para monitorar
# =============================================================================
sites:
  # Aplicação Principal (Staging)
  - name: Blue Cripto App
    url: https://staging.bluecripto.com.br
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 301
      - 302

  # API Health Check
  - name: API
    url: https://staging.bluecripto.com.br/api/health
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200

  # Documentação
  - name: Documentação
    url: https://staging.bluecripto.com.br/docs
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 301
      - 302

# =============================================================================
# Configuração da página de status
# =============================================================================
status-website:
  baseUrl: /
  logoUrl: https://staging.bluecripto.com.br/favicon.ico
  name: Blue Cripto Status
  introTitle: "**Blue Cripto** - Status dos Serviços"
  introMessage: Esta página mostra o status em tempo real de todos os serviços do Blue Cripto. Atualizamos automaticamente a cada 5 minutos.
  theme: dark
  
  navbar:
    - title: Status
      href: /
    - title: App
      href: https://staging.bluecripto.com.br
    - title: Documentação
      href: https://staging.bluecripto.com.br/docs
    - title: Suporte
      href: mailto:suporte@bluecripto.com.br

  i18n:
    activeIncidents: Incidentes Ativos
    allSystemsOperational: Todos os sistemas operacionais
    incidentReport: "Relatório de Incidente: $NUMBER"
    pastIncidents: Incidentes Anteriores
    scheduledMaintenance: Manutenção Programada
    overallUptime: Uptime Geral
    overallResponseTime: Tempo de Resposta
    liveStatus: Status ao Vivo
    responseTime: Tempo de Resposta
    uptime: Uptime
    ms: ms
    loading: Carregando...
    degradedPerformance: Performance Degradada
    completeOutage: Indisponível
    partialOutage: Parcialmente Indisponível

# =============================================================================
# Configurações de Commits
# =============================================================================
commitMessages:
  statusChange: "🔔 $SITE_NAME está $STATUS"
  startCommit: "🚀 Iniciando monitoramento"
  readmeRecap: "📊 Atualizando README com status"
  scheduleCommit: "⏰ Atualização programada"

user-agent: "Blue Cripto Status Monitor/1.0"
