# =============================================================================
# Blue Cripto Status Page - Powered by Upptime
# =============================================================================
# Documentação: https://upptime.js.org/docs/configuration
# =============================================================================

# Informações do repositório GitHub
owner: mychelmendes1
repo: blue-cripto-status

# =============================================================================
# Sites/APIs para monitorar
# =============================================================================
sites:
  # Aplicação Principal
  - name: Blue Cripto App
    url: https://staging.bluecripto.com.br
    icon: https://staging.bluecripto.com.br/favicon.ico
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 301
      - 302

  # API Health Check
  - name: API
    url: https://staging.bluecripto.com.br/api/health
    icon: https://staging.bluecripto.com.br/favicon.ico
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200

  # Documentação
  - name: Documentação
    url: https://staging.bluecripto.com.br/docs
    icon: https://staging.bluecripto.com.br/favicon.ico
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 301
      - 302

  # Staging (opcional - descomente se quiser monitorar)
  # - name: Staging
  #   url: https://staging.bluecripto.com.br
  #   icon: https://staging.bluecripto.com.br/favicon.ico
  #   maxResponseTime: 5000

  # Site Institucional (se existir)
  # - name: Site Institucional
  #   url: https://bluecripto.com.br
  #   maxResponseTime: 5000

# =============================================================================
# Configuração da página de status
# =============================================================================
status-website:
  # Configurações básicas
  cname: status.bluecripto.com.br
  baseUrl: /
  logoUrl: https://staging.bluecripto.com.br/favicon.ico
  name: Blue Cripto Status
  introTitle: "**Blue Cripto** está operacional"
  introMessage: Esta página mostra o status em tempo real de todos os serviços do Blue Cripto. Atualizamos automaticamente a cada 5 minutos.
  
  # Navbar
  navbar:
    - title: Status
      href: /
    - title: App
      href: https://staging.bluecripto.com.br
    - title: Documentação
      href: https://staging.bluecripto.com.br/docs
    - title: Suporte
      href: mailto:suporte@bluecripto.com.br

  # Tema
  theme: dark
  
  # Internacionalização
  i18n:
    activeIncidents: Incidentes Ativos
    allSystemsOperational: Todos os sistemas operacionais
    incidentReport: "Relatório de Incidente: $NUMBER"
    pastIncidents: Incidentes Anteriores
    scheduledMaintenance: Manutenção Programada
    overallUptime: Uptime Geral
    overallResponseTime: Tempo de Resposta
    liveStatus: Status ao Vivo
    responseTime: Tempo de Resposta
    uptime: Uptime
    ms: ms
    loading: Carregando...
    degradedPerformance: Performance Degradada
    completeOutage: Indisponível
    partialOutage: Parcialmente Indisponível
    noIncidents: Nenhum incidente reportado
    day: dia
    days: dias
    hour: hora
    hours: horas
    minute: minuto
    minutes: minutos
    second: segundo
    seconds: segundos
    ago: atrás

# =============================================================================
# Integrações e Notificações
# =============================================================================

# Notificações por Email (via GitHub)
# notifications:
#   - type: email
#     address: suporte@bluecripto.com.br

# Slack (descomente e configure se usar)
# notifications:
#   - type: slack
#     channel: C0XXXXXX

# Discord (descomente e configure se usar)
# notifications:
#   - type: discord

# =============================================================================
# Configurações de Commits
# =============================================================================
commitMessages:
  statusChange: "🔔 $SITE_NAME está $STATUS"
  startCommit: "🚀 Iniciando monitoramento"
  readmeRecap: "📊 Atualizando README com status"
  scheduleCommit: "⏰ Atualização programada"
  commitSummaryTitle: "📊 Resumo de status"

# =============================================================================
# Configurações avançadas
# =============================================================================

# User Agent para requests
user-agent: "Blue Cripto Status Monitor/1.0"

# Intervalo de verificação (em minutos, via cron no workflow)
# O padrão do Upptime é a cada 5 minutos

# Número de dias para manter histórico
# O padrão é 90 dias


